require "Plugins.plugins"
require "globals.options"
require("Plugins.leap")
require "globals.keymaps"

require "Plugins.colorscheme"
require "Plugins.cmp"
require "Plugins.lsp"
require "Plugins.telescope"
require "Plugins.autopairs"
require "globals.compile_function"
require "Plugins.nvim-tree"
require "Plugins.project"
require "Plugins.toggleterm"
require "Plugins.bufferline"
require "Plugins.lsp.null-ls"
--require "Plugins.lualine"
require "globals.highlights"
require "Plugins.gitsigns"
require "Plugins.alpha"
require "Plugins.MarkdownPreview"
require "Plugins.lazygit"
